### ISSUE TITLE
Delete/clean the `Done` column

### ISSUE THREAD

**Issue by lgarest** [diana-moreno/kanban#4]

**Comment by diana-moreno** [comment]
I don't understand this issue. The user is who decides when to delete the 'Done' notes.

**Comment by lgarest** [comment]
What I'm trying to say is that usually, the tasks on `Done` are removed in a batch, so, maybe it's helpful to add a `remove done tasks` feature in its column that delete all the tasks in the `Done` column.

**Comment by lgarest** [comment]
I'll update the task description to make it more clear if you think it's necessary. Maybe you could label this issue with the `enhancement` label.

**Comment by diana-moreno** [comment]
It's a good feature! I've added it, thanks for the idea.
